#!/bin/sh
#
# Starts hostapd
#

PID_FILE=/var/run/hostapd.pid

start() {
	echo -n "Starting hostapd: "
	/usr/sbin/hostapd -B -P $PID_FILE /etc/hostapd.conf
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping hostapd: "
	kill `cat $PID_FILE`
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
